spring:
  security:
    oauth2:
      client:
        provider:
          srf-meteo:
            token-uri: https://api.srgssr.ch/oauth/v1/accesstoken?grant_type=client_credentials
        registration:
          srf-meteo:
            client-id: vhCOppbnnNPlnlonuRqXqIXOzWs9SZKE
            client-secret: R79BNPhRB6IGNN07
            authorization-grant-type: client_credentials
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    username: tea.knezevic@dhimahi.com
    password: 74bdTw33d
    url: jdbc:postgresql://localhost:5431/dyn_price

logging:
  level:
    root: trace